### ISSUE TITLE
 swift  issues 

### ISSUE THREAD

**Issue by RMKitty** [Jvaeyhcd/HcdCachePlayer#6]
i downloaded the demo  and  found  you used  swift  to  write code ,but  it  could't work . Can the HcdCachePlayer  work   by swift ?    the finally  i will  play onLine   but  no cache ,how i to  do

**Comment by Jvaeyhcd** [comment]
This player can work by swift, but maybe it have some bugs.

**Comment by RMKitty** [comment]
oh  thank you
